service: sls-csvtodynamodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'us-west-1'}
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: ${self:service}-csvbucket-${self:provider.stage}
  esbuild:
    bundle: true
    minify: false

plugins:
  - serverless-esbuild

functions:
  csvToDynamoDB:
    handler: handler.csvToDynamoDB
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  # Outputs:
  #   NewOutput:
  #     Description: "Description for the output"
  #     Value: "Some output value"
